// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/customer.proto

// Protobuf Java Version: 3.25.2
package ir.blujr.protobufdemo.common.protobuf.customer;

public final class CustomerProto {
  private CustomerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ir.blujr.protobufdemo.customer.Customers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    java.util.List<CustomerProto.Customer>
        getCustomerList();
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    CustomerProto.Customer getCustomer(int index);
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    int getCustomerCount();
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    java.util.List<? extends CustomerProto.CustomerOrBuilder>
        getCustomerOrBuilderList();
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    CustomerProto.CustomerOrBuilder getCustomerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ir.blujr.protobufdemo.customer.Customers}
   */
  public static final class Customers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ir.blujr.protobufdemo.customer.Customers)
      CustomersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customers.newBuilder() to construct.
    private Customers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customers() {
      customer_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customers();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerProto.Customers.class, CustomerProto.Customers.Builder.class);
    }

    public static final int CUSTOMER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<CustomerProto.Customer> customer_;
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    @java.lang.Override
    public java.util.List<CustomerProto.Customer> getCustomerList() {
      return customer_;
    }
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends CustomerProto.CustomerOrBuilder>
        getCustomerOrBuilderList() {
      return customer_;
    }
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    @java.lang.Override
    public int getCustomerCount() {
      return customer_.size();
    }
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    @java.lang.Override
    public CustomerProto.Customer getCustomer(int index) {
      return customer_.get(index);
    }
    /**
     * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
     */
    @java.lang.Override
    public CustomerProto.CustomerOrBuilder getCustomerOrBuilder(
        int index) {
      return customer_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customer_.size(); i++) {
        output.writeMessage(1, customer_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < customer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customer_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CustomerProto.Customers)) {
        return super.equals(obj);
      }
      CustomerProto.Customers other = (CustomerProto.Customers) obj;

      if (!getCustomerList()
          .equals(other.getCustomerList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomerCount() > 0) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CustomerProto.Customers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProto.Customers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProto.Customers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProto.Customers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProto.Customers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerProto.Customers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CustomerProto.Customers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CustomerProto.Customers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerProto.Customers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomerProto.Customers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ir.blujr.protobufdemo.customer.Customers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ir.blujr.protobufdemo.customer.Customers)
        CustomerProto.CustomersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerProto.Customers.class, CustomerProto.Customers.Builder.class);
      }

      // Construct using ir.blujr.protobufdemo.customer.CustomerProto.Customers.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
        } else {
          customer_ = null;
          customerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customers_descriptor;
      }

      @java.lang.Override
      public CustomerProto.Customers getDefaultInstanceForType() {
        return CustomerProto.Customers.getDefaultInstance();
      }

      @java.lang.Override
      public CustomerProto.Customers build() {
        CustomerProto.Customers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CustomerProto.Customers buildPartial() {
        CustomerProto.Customers result = new CustomerProto.Customers(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(CustomerProto.Customers result) {
        if (customerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            customer_ = java.util.Collections.unmodifiableList(customer_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
      }

      private void buildPartial0(CustomerProto.Customers result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProto.Customers) {
          return mergeFrom((CustomerProto.Customers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomerProto.Customers other) {
        if (other == CustomerProto.Customers.getDefaultInstance()) return this;
        if (customerBuilder_ == null) {
          if (!other.customer_.isEmpty()) {
            if (customer_.isEmpty()) {
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomerIsMutable();
              customer_.addAll(other.customer_);
            }
            onChanged();
          }
        } else {
          if (!other.customer_.isEmpty()) {
            if (customerBuilder_.isEmpty()) {
              customerBuilder_.dispose();
              customerBuilder_ = null;
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customerBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCustomerFieldBuilder() : null;
            } else {
              customerBuilder_.addAllMessages(other.customer_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                CustomerProto.Customer m =
                    input.readMessage(
                        CustomerProto.Customer.parser(),
                        extensionRegistry);
                if (customerBuilder_ == null) {
                  ensureCustomerIsMutable();
                  customer_.add(m);
                } else {
                  customerBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<CustomerProto.Customer> customer_ =
        java.util.Collections.emptyList();
      private void ensureCustomerIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          customer_ = new java.util.ArrayList<CustomerProto.Customer>(customer_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          CustomerProto.Customer, CustomerProto.Customer.Builder, CustomerProto.CustomerOrBuilder> customerBuilder_;

      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public java.util.List<CustomerProto.Customer> getCustomerList() {
        if (customerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customer_);
        } else {
          return customerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public int getCustomerCount() {
        if (customerBuilder_ == null) {
          return customer_.size();
        } else {
          return customerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public CustomerProto.Customer getCustomer(int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);
        } else {
          return customerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder setCustomer(
          int index, CustomerProto.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.set(index, value);
          onChanged();
        } else {
          customerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder setCustomer(
          int index, CustomerProto.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.set(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder addCustomer(CustomerProto.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(value);
          onChanged();
        } else {
          customerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          int index, CustomerProto.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(index, value);
          onChanged();
        } else {
          customerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          CustomerProto.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          int index, CustomerProto.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder addAllCustomer(
          java.lang.Iterable<? extends CustomerProto.Customer> values) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customer_);
          onChanged();
        } else {
          customerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public Builder removeCustomer(int index) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.remove(index);
          onChanged();
        } else {
          customerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public CustomerProto.Customer.Builder getCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public CustomerProto.CustomerOrBuilder getCustomerOrBuilder(
          int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);  } else {
          return customerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public java.util.List<? extends CustomerProto.CustomerOrBuilder>
           getCustomerOrBuilderList() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customer_);
        }
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public CustomerProto.Customer.Builder addCustomerBuilder() {
        return getCustomerFieldBuilder().addBuilder(
            CustomerProto.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public CustomerProto.Customer.Builder addCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().addBuilder(
            index, CustomerProto.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .ir.blujr.protobufdemo.customer.Customer customer = 1;</code>
       */
      public java.util.List<CustomerProto.Customer.Builder>
           getCustomerBuilderList() {
        return getCustomerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          CustomerProto.Customer, CustomerProto.Customer.Builder, CustomerProto.CustomerOrBuilder>
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              CustomerProto.Customer, CustomerProto.Customer.Builder, CustomerProto.CustomerOrBuilder>(
                  customer_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ir.blujr.protobufdemo.customer.Customers)
    }

    // @@protoc_insertion_point(class_scope:ir.blujr.protobufdemo.customer.Customers)
    private static final CustomerProto.Customers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomerProto.Customers();
    }

    public static CustomerProto.Customers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customers>
        PARSER = new com.google.protobuf.AbstractParser<Customers>() {
      @java.lang.Override
      public Customers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Customers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CustomerProto.Customers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ir.blujr.protobufdemo.customer.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code ir.blujr.protobufdemo.customer.Customer}
   */
  public static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ir.blujr.protobufdemo.customer.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customer();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomerProto.Customer.class, CustomerProto.Customer.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CustomerProto.Customer)) {
        return super.equals(obj);
      }
      CustomerProto.Customer other = (CustomerProto.Customer) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CustomerProto.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProto.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProto.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomerProto.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomerProto.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerProto.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CustomerProto.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CustomerProto.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomerProto.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomerProto.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ir.blujr.protobufdemo.customer.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ir.blujr.protobufdemo.customer.Customer)
        CustomerProto.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomerProto.Customer.class, CustomerProto.Customer.Builder.class);
      }

      // Construct using ir.blujr.protobufdemo.customer.CustomerProto.Customer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        name_ = "";
        email_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomerProto.internal_static_ir_blujr_protobufdemo_customer_Customer_descriptor;
      }

      @java.lang.Override
      public CustomerProto.Customer getDefaultInstanceForType() {
        return CustomerProto.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public CustomerProto.Customer build() {
        CustomerProto.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CustomerProto.Customer buildPartial() {
        CustomerProto.Customer result = new CustomerProto.Customer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CustomerProto.Customer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.email_ = email_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomerProto.Customer) {
          return mergeFrom((CustomerProto.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomerProto.Customer other) {
        if (other == CustomerProto.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ir.blujr.protobufdemo.customer.Customer)
    }

    // @@protoc_insertion_point(class_scope:ir.blujr.protobufdemo.customer.Customer)
    private static final CustomerProto.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomerProto.Customer();
    }

    public static CustomerProto.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CustomerProto.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_blujr_protobufdemo_customer_Customers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_blujr_protobufdemo_customer_Customers_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_blujr_protobufdemo_customer_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_blujr_protobufdemo_customer_Customer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/resources/customer.proto\022\036ir." +
      "blujr.protobufdemo.customer\"G\n\tCustomers" +
      "\022:\n\010customer\030\001 \003(\0132(.ir.blujr.protobufde" +
      "mo.customer.Customer\"3\n\010Customer\022\n\n\002id\030\001" +
      " \001(\003\022\014\n\004name\030\002 \001(\t\022\r\n\005email\030\003 \001(\tB\017B\rCus" +
      "tomerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ir_blujr_protobufdemo_customer_Customers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ir_blujr_protobufdemo_customer_Customers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_blujr_protobufdemo_customer_Customers_descriptor,
        new java.lang.String[] { "Customer", });
    internal_static_ir_blujr_protobufdemo_customer_Customer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ir_blujr_protobufdemo_customer_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_blujr_protobufdemo_customer_Customer_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
